[0.0.2]
Title = "Version 0.0.2"
Description = [ "Clean up config files.", "Clean up config files.",]
GitHubIssues = [4]

Title = "Version 0.0.1"
Description = [ "Add the meat to the skeleton.", "Clean up config files.", "Clean up config files.",]
GitHubIssues = [1, 2, 3]

[0.0.0]
Title = "Version 0.0.0"
Description = [ "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
GitHubIssues = []
