name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Requirements for Prod
        run:  pip install -r requirements.txt

      - name: Install Requirements for Test
        run:  pip install -r requirements_test.txt

      - name: Install Code
        run:  pip install -e .

      - name: Change Access to MySQL Config File
        run:  sudo chmod 444 /etc/mysql/mysql.conf.d/mysqld.cnf

      - name: Run tests
        run: pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
